mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
import login.urls
import todo.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(login.urls)),
    path('todo/', include(todo.urls)),
]

todo/urls.py
from django.urls import path,include
from . import views

app_name='todo'

urlpatterns = [
    path('', views.home,name="主页"),
    path('about/',views.about,name="关于"),
    path('edit/<i_id>',views.edit,name="编辑"),
    path('delete/<i_id>',views.delete,name="删除"),
    path('cross/<i_id>',views.cross,name="划掉"),
    path('edit_level/<i_id>',views.edit_level,name="优先级"),
    path('details/<i_id>',views.details,name="详细内容"),
]

todo/models.py
from typing import Match
from django.db import models


# Create your models here.
class Todolist(models.Model):

    thing =models.CharField(max_length=50)

    done=models.BooleanField(default=True)

    level=models.IntegerField(default=0)

    details=models.CharField(max_length=5000,default="")

    def __str__(self):

        return self.thing

todo/views.py
from django.shortcuts import redirect, render,HttpResponse
from django import forms
from django.forms import widgets
from .models import Todolist
# Create your views here.
class RegForm(forms.Form):
    thing= forms.CharField(required=True,error_messages={
        "required":"待办清单不能为空",
    })
    level= forms.IntegerField(max_value=99,min_value=1,required=True,error_messages={
        "max_value":"最大值99",
        "min_value":"最小值1",
        "required":"优先级不能为空",})

class Reg_Form(forms.Form):
    level= forms.IntegerField(max_value=99,min_value=1,required=True,error_messages={
        "max_value":"最大值99",
        "min_value":"最小值1",
        "required":"优先级不能为空",})

def home(request):
    if request.method =="POST":
        thing=request.POST.get("thing")
        level=request.POST.get("level")
        obj = RegForm(request.POST)
        if obj.is_valid():
            a_row=Todolist(thing=thing,done=False,level=level,details=" ")
            a_row.save()
            content={"清单":Todolist.objects.all().order_by('done','-level'),"信息":"添加成功"}
            return render(request,"home.html",content)
        else:
            content={"清单":Todolist.objects.all().order_by('done','-level'),"警告":"添加失败"}
            return render(request,"home.html",content)

    elif request.method =="GET":
        content={"清单":Todolist.objects.all().order_by('done','-level')}
        return render(request,"home.html",content)
        
def about(request):

    return render(request,"about.html")

def edit(request,i_id):
    if request.method=="POST":
        if request.POST["已修改事项"]=="":
            return render(request,"edit.html",{"警告":"请输入内容！"})
        else:
            a=Todolist.objects.get(id=i_id)
            a.thing=request.POST["已修改事项"]
            a.save()
            return redirect("todo:主页")
    elif request.method=="GET":
        content={'待修改事项': Todolist.objects.get(id=i_id).thing}
        return render(request,"edit.html",content)

def details(request,i_id):
    if request.method=="POST":
        g=request.POST.get("已修改详细内容")
        a=Todolist.objects.get(id=i_id)
        a.details=g
        a.save()
        return redirect("todo:主页")

    elif request.method=="GET":
        content={'待修改详细内容': Todolist.objects.get(id=i_id).details}
        return render(request,"details.html",content)


def edit_level(request,i_id):

    if request.method=="POST":
        level=request.POST.get("level")
        obj = Reg_Form(request.POST)
        if obj.is_valid():
            a=Todolist.objects.get(id=i_id)
            a.level=level
            a.save()
            return redirect("todo:主页")
        else:
            return render(request,"edit_level.html",{"警告":"请输入内容！"})

    elif request.method=="GET":
        content={'level': Todolist.objects.get(id=i_id).level}
        return render(request,"edit_level.html",content)

def delete(request,i_id):
    a=Todolist.objects.get(id=int(i_id))
    a.delete()
    return redirect("todo:主页")
    
def cross(request,i_id):
    if request.POST["完成状态"]=="已完成":
        a=Todolist.objects.get(id=i_id)
        a.done=True
        a.save()
        return redirect("todo:主页")
    elif request.POST["完成状态"]=="未完成":
        a=Todolist.objects.get(id=i_id)
        a.done=False
        a.save()    
        return redirect("todo:主页")

todo/templates/about.html
{% extends 'base.html' %}
{% block 标题 %}关于本站{% endblock 标题 %}
{% block 关于高亮 %}active{% endblock 关于高亮 %}
{% block 主体 %}
<br>
<h4>本站是为了更好的计划生活，用于计划、记录生活项目。</h4>

{% endblock 主体 %}

todo/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block css %}{% static 'css/edit.css' %}{% endblock css %}
{% block 标题 %}详细内容{% endblock 标题 %}
{% block content %}
<br>
<form method="POST" action="">
    {% csrf_token %}
    <div class="from-group">
        <label for="editTodo"></label>
        <textarea class="form-control" rows="10" name="已修改详细内容">{{ 待修改详细内容 }}</textarea>
        {% comment %} <input name="已修改详细内容" class="form-control form-control-lg" id="editTodo" type="text"> {% endcomment %}
        <small id="help" class="form-text text-muted">在这里编辑详细内容</small>
    </div>
    {% if 警告 %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><center>{{ 警告 }}</center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endif %}
    <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>
{% endblock content %}

todo/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block css %}{% static 'css/edit.css' %}{% endblock css %}
{% block 标题 %}编辑{% endblock 标题 %}
{% block content %}
<br>
<form id="form-edit" method="POST" action="">
    {% csrf_token %}
    <div class="from-group">
        <label for="editTodo"></label>
        <input name="已修改事项" class="form-control form-control-lg" id="editTodo" type="text" value="{{ 待修改事项 }}">
        <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
    </div>
    {% if 警告 %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><center>{{ 警告 }}</center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endif %}
    <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>
{% endblock content %}

todo/templates/edit_level.html
{% extends 'base.html' %}
{% load static %}
{% block css %}{% static 'css/edit.css' %}{% endblock css %}
{% block 标题 %}优先级{% endblock 标题 %}
{% block content %}
<br>
<form id="form-edit" method="POST" action="">
    {% csrf_token %}
    <div class="from-group">
        <label for="editTodo"></label>
        <input name="level" class="form-control form-control-lg" id="editTodo" type="text" value="{{level}}">
        <small id="help" class="form-text text-muted">在这里编辑优先级</small>
    </div>
    {% if 警告 %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><center>{{ 警告 }}</center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endif %}
    <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>
{% endblock content %}

todo/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% comment %} {% block css %}{% static 'css/home.css' %}{% endblock css %} {% endcomment %}
{% block content %}
{% comment %} {% if 警告 %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<strong><center>{{ 警告 }}</center></strong>
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %}
{% if 信息 %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
<strong><center>{{ 信息 }}</center></strong>
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %} {% endcomment %}

<div class ="table-responsive">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>序号</th>
        <th>待办事项</th>
        <th>优先级</th>
        <th>编辑</th>
        <th>划掉</th>
        <th>删除</th>
      </tr>
    </thead>
    <tbody class="no-underline">
    {% for i in 清单 %}
      {% if i.done %}
        </tr>
          <tr class="table-dark">
          <th class="text-dark" scope="row">{{ forloop.counter }}</th>
          <td class="text-dark" id="line-through">{{ i.thing }}</td>
          <td class="text-dark" id="line-through">{{i.level}}</td>
          <td class="text-secondary">不可编辑</td>
          <td>
            <form method="POST" action="{% url 'todo:划掉' i.id %}">
            {% csrf_token %}
            <input name="完成状态" type="hidden" value="未完成">
            <button type="submit" class="btn btn-primary btn-sm">撤销</button>
            </form>
          </td>
          <td>            
            <form method="POST" action="{% url 'todo:删除' i.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">删除</button>
            </form>
          </td>
        </tr> 
      {% else %}
        <tr>
          <th class="text-dark" scope="row">{{ forloop.counter }}</th>
          <td>
            <a href="{% url 'todo:详细内容' i.id %}">
            {{i.thing}}
            </a>
          </td>
          <td>            
            <a href="{% url 'todo:优先级' i.id %}">
            <button type ="submit" class = "btn btn-primary btn-sm">{{i.level}}</button>
           </a>
          </td>
          <td>
            <a href="{% url 'todo:编辑' i.id %}">
              <button type ="submit" class = "btn btn-primary btn-sm">编辑</button>
            </a>
          </td>
          <td>
            <form method="POST" action="{% url 'todo:划掉' i.id %}">
            {% csrf_token %}
            <input name="完成状态" type="hidden" value="已完成">
            <button type="submit" class="btn btn-primary btn-sm">划掉</button>
            </form>
          </td>
          <td>

            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModal{{forloop.counter}}">删除</button>

            <div class="modal fade" id="exampleModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModal{{forloop.counter}}Label" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal{{forloop.counter}}Label">请确认</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  </div>
                  <div class="modal-body">
                  确定要删除：<strong>未办事项 {{ i.thing }}</strong> 吗？
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"> 取消</button>
                  <form method="POST" action="{% url 'todo:删除' i.id %}">
                    {% csrf_token %}       
                  <button type="submit" class="btn btn-primary">确认</button>
                  </form>
                  </div>
                </div>
              </div>
            </div>
          </td>
        </tr>
      
      {% endif %}

    {% endfor %}
    <button type="button" class="btn btn-danger my-2 my-sm-0" style="float:right" data-toggle="modal" data-target="#modellevel">+</button>

    <div class="modal fade" id="modellevel" tabindex="-1" role="dialog" aria-labelledby="modellevelLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modellevelLabel">请确认</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <div class="modal-body">
            <form method="POST" action="{% url 'todo:主页' %}" enctype="multipart/form-data">
              <input name='thing' class="form-control mr-sm-2" type="text" placeholder='待办事项'>
              <input name='level' class="form-control mr-sm-2" type="text" placeholder='优先级'>
              <button type="button" class="btn btn-secondary" data-dismiss="modal"> 取消</button>    
              <button type="submit" class="btn btn-primary">确认</button>
              {% csrf_token %}   
            </form>
            </div>
          </div>
        </div>
      </div>
    </div> 
</div>
<br><br>
    </tbody>
  </table>
</div>
{% endblock content %}